import { Job } from '@/types/job'

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Update Model Range PDF',
    client: 'BMW',
    brief: 'Update the 2025 model range PDF with new pricing and specs.',
    type: 'Content update',
    priority: 'p1',
    status: 'in-progress',
    am: 'Sarah M',
    due_date: '2026-04-22',
    assets: true,
    asset_notes: null,
    workbook_link: 'https://wb.ogilvy.co.za#84b5fb8c625',
    is_fire_alarm: false,
    created_at: '2026-04-20T08:00:00Z',
    updated_at: '2026-04-21T09:00:00Z',
    completed_at: null,
  },
  {
    id: '2',
    title: 'Homepage banner broken on mobile',
    client: 'Audi',
    brief: 'The hero banner is not rendering correctly on iOS Safari.',
    type: 'Urgent fix',
    priority: 'p1',
    status: 'briefed',
    am: 'James K',
    due_date: '2026-04-21',
    assets: true,
    asset_notes: null,
    workbook_link: null,
    is_fire_alarm: true,
    created_at: '2026-04-21T07:30:00Z',
    updated_at: '2026-04-21T07:30:00Z',
    completed_at: null,
  },
  {
    id: '3',
    title: 'Q2 HTML Emailer',
    client: 'Mercedes',
    brief: null,
    type: 'HTML emailer',
    priority: 'p2',
    status: 'briefed',
    am: 'Sarah M',
    due_date: '2026-04-25',
    assets: true,
    asset_notes: null,
    workbook_link: 'https://wb.ogilvy.co.za#c3d4e5f6',
    is_fire_alarm: false,
    created_at: '2026-04-19T10:00:00Z',
    updated_at: '2026-04-19T10:00:00Z',
    completed_at: null,
  },
  {
    id: '4',
    title: 'New Campaign Landing Page',
    client: 'VW',
    brief: 'Summer campaign page with video hero and model grid.',
    type: 'Campaign page',
    priority: 'p2',
    status: 'awaiting-assets',
    am: 'Lisa T',
    due_date: '2026-04-30',
    assets: false,
    asset_notes: 'Waiting on hero video from client. ETA Friday.',
    workbook_link: 'https://wb.ogilvy.co.za#a1b2c3d4',
    is_fire_alarm: false,
    created_at: '2026-04-18T14:00:00Z',
    updated_at: '2026-04-21T08:00:00Z',
    completed_at: null,
  },
  {
    id: '5',
    title: 'Copy update — T&Cs page',
    client: 'BMW',
    brief: null,
    type: 'Copy change',
    priority: 'p3',
    status: 'needs-info',
    am: 'James K',
    due_date: null,
    assets: false,
    asset_notes: 'Need updated copy from legal team.',
    workbook_link: null,
    is_fire_alarm: false,
    created_at: '2026-04-17T11:00:00Z',
    updated_at: '2026-04-17T11:00:00Z',
    completed_at: null,
  },
  {
    id: '6',
    title: 'Asset upload — new model imagery',
    client: 'Audi',
    brief: 'Upload 12 new model images to the CMS.',
    type: 'New asset upload',
    priority: 'p3',
    status: 'in-review',
    am: 'Sarah M',
    due_date: '2026-04-23',
    assets: true,
    asset_notes: null,
    workbook_link: 'https://wb.ogilvy.co.za#f7e8d9c0',
    is_fire_alarm: false,
    created_at: '2026-04-16T09:00:00Z',
    updated_at: '2026-04-21T10:00:00Z',
    completed_at: null,
  },
  {
    id: '7',
    title: 'Dealer locator bug fix',
    client: 'Mercedes',
    brief: 'Dealer locator returning wrong results for Cape Town.',
    type: 'Bug fix',
    priority: 'p2',
    status: 'live',
    am: 'Lisa T',
    due_date: '2026-04-20',
    assets: true,
    asset_notes: null,
    workbook_link: 'https://wb.ogilvy.co.za#b2c3d4e5',
    is_fire_alarm: false,
    created_at: '2026-04-14T08:00:00Z',
    updated_at: '2026-04-20T16:00:00Z',
    completed_at: '2026-04-20T16:00:00Z',
  },
]
